### ISSUE TITLE
Setup Pictures?

### ISSUE THREAD

**Issue by Xylopyrographer** [stuart-brown/ArduinoShutterSpeedTester#1]
Hi. Wondering if you could post a few pictures or a diagram of the physical layout of the three lasers and photo receivers? Particularly curious about alignment when measuring focal plane curtain shutters. As well shielding of the receivers to avoid ambient light and laser cross-talk. Many thanks.

**Comment by stuart-brown** [comment]
Hi, Thanks for the question. I built the tester using an old macro bellows and 3D printed parts. The lasers are held in a ball and sockets mount so they can be adjusted to shine into the photoreceptors. I intend to update the repo with the models and some photos, but I've been a bit busy with work and other things, so keep a watch on it.

**Comment by stuart-brown** [comment]
Build details added to readme, together with STL files for 3D printed parts and lots of images
